import assert from 'node:assert/strict'
import { recognize } from './recognition.ts'
const now = new Date(2026, 11, 31, 12)
assert.equal(recognize('회의 내일 오후 3시', [], [], now).due_at, '2027-01-01T15:00')
assert.equal(recognize('회의 내일 오후 3시', [], [], now).title, '회의')
assert.equal(recognize('배포 2027-02-30', [], [], now).title, '배포 2027-02-30')
assert.equal(recognize('알림 25시', [], [], now).due_at, null)
assert.equal(recognize('매일 운동', [], [], now).repeat_rule, 'FREQ=DAILY')
assert.equal(recognize('매주 월요일 운동', [], [], now).due_at, '2027-01-04')
assert.equal(recognize('다음 주 금요일 회의', [], [], now).due_at, '2027-01-08')
assert.equal(recognize('내일의 계획', [], [], now).title, '내일의 계획')
const r = recognize('기획 #업무 ~회사 !높음', [{id:'l',name:'회사'}], [{id:'t',name:'업무'}], now)
assert.deepEqual([r.title,r.list_id,r.tag_ids,r.priority], ['기획','l',['t'],3])
assert.equal(recognize('작업 #없는태그').title, '작업 #없는태그')
// E2E(2026-10-04): 요일만 쓴 '금요일 오전 10시 보고서'가 오늘 10시로 잡히던 것
assert.equal(recognize('금요일 오전 10시 보고서 제출', [], [], now).due_at, '2027-01-01T10:00')
assert.equal(recognize('금요일 오전 10시 보고서 제출', [], [], now).title, '보고서 제출')
assert.equal(recognize('목요일 회의', [], [], now).due_at, '2026-12-31')
assert.equal(recognize('월요일엔 쉬기', [], [], now).due_at, null)
// 고유어 시각 — 날짜와 같이, 강조 토큰이 말을 다 덮는다(2026-10-06)
const nat = recognize('내일 세시 반 공모전 회의', [], [], now)
assert.deepEqual([nat.due_at, nat.title], ['2027-01-01T03:30', '공모전 회의'])
assert.ok(nat.recognized.includes('세시 반'), '강조 = "세시 반" 전체')
const pmNat = recognize('내일 오후 세시 공모전', [], [], now)
assert.deepEqual([pmNat.due_at, pmNat.title, pmNat.recognized], ['2027-01-01T15:00', '공모전', ['내일', '오후 세시']])
assert.equal(recognize('저녁 일곱시 20분 운동', [], [], now).due_at, '2026-12-31T19:20')
assert.equal(recognize('모레 밤 열한시 정각 마감', [], [], now).due_at, '2027-01-02T23:00')
assert.equal(recognize('아침 열시 산책', [], [], now).title, '산책')
assert.equal(recognize('3시 반 미팅', [], [], now).due_at, '2026-12-31T03:30')
assert.equal(recognize('한시간 공부', [], [], now).due_at, null, '"한시간"은 시각이 아님')
assert.equal(recognize('세시간 운동', [], [], now).title, '세시간 운동')
assert.equal(recognize('밤 산책', [], [], now).title, '밤 산책')
console.log('recognition: 26 assertions passed')
