import { saveNote, convertNote } from '../src/renderer/src/data/notes'
import { timeSelection } from '../src/renderer/src/lib/calendarSelection'
import { createCalendarTask } from '../src/renderer/src/data/calendarCreate'
import assert from 'node:assert/strict'
import initSqlJs from 'sql.js'
import { TABLES } from '@sprout/schema'
import { saveOrganization, archiveList, deleteOrganization } from '../src/renderer/src/data/organization'
import { createTask, insert, run } from '../src/renderer/src/data/mutations'
import { openTasksSql, defaultSettings } from '../src/renderer/src/data/views'
import { scheduledDrop } from '../src/renderer/src/lib/calendarDrop'
const SQL = await initSqlJs()
const db = new SQL.Database()
for (const [name, def] of Object.entries(TABLES)) db.run(`CREATE TABLE ${name} (id TEXT PRIMARY KEY, ${Object.keys(def.columns).join(', ')})`)
const all = (sql:string, params:unknown[]=[]) => {const s=db.prepare(sql);s.bind(params as never);const r:Record<string,unknown>[]=[];while(s.step())r.push(s.getAsObject());s.free();return r}
Object.assign(globalThis,{window:{sprout:{db:{getAll:async(sql:string,p?:unknown[])=>all(sql,p),get:async(sql:string,p?:unknown[])=>all(sql,p)[0]??null,transaction:async(stmts:{sql:string;params?:unknown[]}[])=>{db.run('BEGIN');try{for(const s of stmts)db.run(s.sql,s.params as never);db.run('COMMIT')}catch(e){db.run('ROLLBACK');throw e}}}}}})
const f=await saveOrganization('folder',undefined,{name:' Project '})
assert.equal(all('SELECT name FROM folders')[0].name,'Project')
const l=await saveOrganization('list',undefined,{name:'Work',folder_id:f})
const t=await createTask({title:'Preserved task',list_id:l,due_at:'2026-10-04'})
const query=(view:string)=>{const q=openTasksSql(view,defaultSettings(view),'2026-10-04');return all(q.sql,q.params)}
assert.equal(query(`folder:${f}`).length,1)
await archiveList(l,true)
assert.equal(query('smart:all').length,0)
assert.equal(query(`list:${l}`).length,1)
await archiveList(l,false)
assert.equal(query('smart:all').length,1)
await deleteOrganization('folder',f)
assert.equal(all('SELECT folder_id FROM lists WHERE id=?',[l])[0].folder_id,null)
assert.equal(all('SELECT title FROM tasks WHERE id=?',[t])[0].title,'Preserved task')
const tag=await saveOrganization('tag',undefined,{name:'Parent'})
const child=await saveOrganization('tag',undefined,{name:'Child',parent_id:tag})
await run(insert('task_tags',{id:'link',task_id:t,tag_id:tag}))
await assert.rejects(()=>saveOrganization('tag',tag,{name:'Parent',parent_id:child}),/2단계/)
await assert.rejects(()=>saveOrganization('tag',child,{name:'Child',parent_id:child}),/2단계/)
await deleteOrganization('tag',tag)
assert.equal(all('SELECT * FROM task_tags').length,0)
assert.equal(all('SELECT parent_id FROM tags WHERE id=?',[child])[0].parent_id,null)
assert.equal(all('SELECT * FROM tasks').length,1)
await deleteOrganization('list',l)
assert.equal(query('smart:trash').length,1)
assert.ok(all('SELECT archived_at FROM lists WHERE id=?',[l])[0].archived_at)
const inbox=await saveOrganization('list',undefined,{name:'Inbox',kind:'inbox'})
await assert.rejects(()=>archiveList(inbox,true),/기본함/)
await assert.rejects(()=>deleteOrganization('list',inbox),/기본함/)
await assert.rejects(()=>saveOrganization('tag',undefined,{name:' '}),/이름/)
assert.deepEqual(scheduledDrop({id:'a',start_at:null,due_at:null},{day:'2026-12-31',minute:1425}),{id:'a',start_at:'2026-12-31T23:45',due_at:'2027-01-01T00:45'})
assert.deepEqual(scheduledDrop({id:'a',start_at:'2026-10-01T09:00',due_at:'2026-10-01T10:30'},{day:'2026-10-04',minute:600}),{id:'a',start_at:'2026-10-04T10:00',due_at:'2026-10-04T11:30'})
assert.deepEqual(scheduledDrop({id:'a',start_at:'2026-10-01T09:00',due_at:'2026-10-01T10:30'},{day:'2026-10-04'}),{id:'a',start_at:null,due_at:'2026-10-04'})
const filterList=await saveOrganization('list',undefined,{name:'Filter QA'})
const target=await createTask({title:'literal 100%_ work',list_id:filterList,due_at:'2026-10-04',priority:3})
const other=await createTask({title:'different work',list_id:filterList,due_at:'2026-10-05',priority:1})
await run(insert('task_tags',{id:'filter-link',task_id:target,tag_id:child}),insert('filters',{id:'filter-qa',name:'QA',rule_json:JSON.stringify({lists:[filterList],tags:[child],date:'today',priorities:[3],keyword:'100%_'})}))
assert.deepEqual(query('filter:filter-qa').map(t=>t.id),[target])
assert.equal(query('filter:missing').length,0)
await run({sql:'UPDATE filters SET rule_json=? WHERE id=?',params:['{broken','filter-qa']})
assert.equal(query('filter:filter-qa').length,0)
await run({sql:'UPDATE filters SET rule_json=? WHERE id=?',params:[JSON.stringify({date:'tomorrow'}),'filter-qa']})
assert.deepEqual(query('filter:filter-qa').map(t=>t.id),[other])
await archiveList(filterList,true)
assert.equal(query('filter:filter-qa').length,0)
const span={start_at:'2026-10-06T09:00',due_at:'2026-10-06T10:30',is_all_day:0,repeat_rule:null,repeat_from:null,reminders:['-PT0M']}
assert.deepEqual(timeSelection('2026-10-07',660,660),{start_at:null,due_at:'2026-10-07T11:00'})
assert.deepEqual(timeSelection('2026-10-07',660,720),{start_at:'2026-10-07T11:00',due_at:'2026-10-07T12:15'})
assert.deepEqual(timeSelection('2026-10-07',720,660),timeSelection('2026-10-07',660,720))
assert.deepEqual(timeSelection('2026-10-07',1425,1425),{start_at:null,due_at:'2026-10-07T23:45'})
const cal=await createCalendarTask('Calendar creation',inbox,0,span,'Calendar note')
assert.equal(all('SELECT content FROM tasks WHERE id=?',[cal])[0].content,'Calendar note')
assert.equal(all('SELECT start_at FROM tasks WHERE id=?',[cal])[0].start_at,span.start_at)
assert.equal(all('SELECT trigger FROM reminders WHERE task_id=?',[cal])[0].trigger,'-PT0M')
db.run("CREATE TRIGGER reject_reminder BEFORE INSERT ON reminders BEGIN SELECT RAISE(ABORT, 'test failure'); END")
await assert.rejects(()=>createCalendarTask('Must rollback',inbox,0,span),/test failure/)
assert.equal(all("SELECT id FROM tasks WHERE title='Must rollback'").length,0)
db.run('DROP TRIGGER reject_reminder')
await assert.rejects(()=>saveNote('  '),/입력/)
const memo=await saveNote('100%_ 메모\nhttps://example.com')
await saveNote('수정된 메모\n원문 설명',memo)
const converted=await convertNote(memo,{title:'메모에서 생성',listId:inbox,due:'2026-10-08T16:00',start:'2026-10-08T15:00'})
assert.equal(all('SELECT content FROM tasks WHERE id=?',[converted])[0].content,'수정된 메모\n원문 설명')
assert.equal(all('SELECT task_id FROM notes WHERE id=?',[memo])[0].task_id,converted)
assert.equal(await convertNote(memo,{title:'중복',listId:inbox}),converted)
assert.equal(all('SELECT id FROM tasks WHERE id=?',[converted]).length,1)
const invalidNote=await saveNote('잘못된 기간')
await assert.rejects(()=>convertNote(invalidNote,{title:'오류',listId:inbox,start:'2026-10-08T17:00',due:'2026-10-08T16:00'}),/종료/)
db.run("CREATE TRIGGER reject_note_link BEFORE UPDATE OF task_id ON notes BEGIN SELECT RAISE(ABORT, 'note failure'); END")
await assert.rejects(()=>convertNote(invalidNote,{title:'롤백',listId:inbox}),/note failure/)
assert.equal(all('SELECT id FROM tasks WHERE id=?',['note-'+invalidNote]).length,0)
db.run('DROP TRIGGER reject_note_link')
db.close()
console.log('desktop data and filter assertions passed')
