import { useCallback, useEffect, useRef, useState } from 'react'
import { ArrowUpRight, RefreshCw, Plus, Gauge, EyeOff, Pencil, Check, X } from 'lucide-react'
import { usageProviders,usageInfo,quotaIsStale,type UsageProvider,type UsageSnapshot,type QuotaAccount,type UsageLogin } from '../../../shared/usage'
import { readUsage,startUsageLogin,usageLoginStatus,cancelUsageLogin,submitUsageLoginCode } from '../data/usage'
import { useLocalState } from '../data/preferences'
import './usage.css'
type Preferences=Record<string,{alias?:string;hidden?:boolean}>
const statuses={fresh:'최신',stale:'마지막 확인값',auth_required:'재인증 필요',unavailable:'조회 불가',unsupported:'미지원',error:'조회 오류'}
function resetLabel(value:string|null,now:number){if(!value)return '초기화 시각 미제공';const ms=Date.parse(value)-now;if(ms<=0)return '초기화 시각 경과 · 재조회 필요';const minutes=Math.ceil(ms/60000);return `${minutes>=1440?`${Math.floor(minutes/1440)}일 `:''}${Math.floor(minutes%1440/60)}시간 ${minutes%60}분 후 초기화`}
export function UsageView(){
 const [snapshots,setSnapshots]=useState<Partial<Record<UsageProvider,UsageSnapshot>>>({}),[busy,setBusy]=useState<Partial<Record<UsageProvider,boolean>>>({}),[errors,setErrors]=useState<Partial<Record<UsageProvider,string>>>({})
 const [filter,setFilter]=useState<UsageProvider|'all'>('all'),[showHidden,setShowHidden]=useState(false),[connecting,setConnecting]=useState(false),[notice,setNotice]=useState(''),[now,setNow]=useState(Date.now())
 const [preferences,setPreferences]=useLocalState<Preferences>('sprout.usage.display',{})
 const [authCode,setAuthCode]=useState('')
 const [login,setLogin]=useState<UsageLogin|null>(null),[loginBusy,setLoginBusy]=useState(false)
 const loginRef=useRef<UsageLogin|null>(null)
 const connectButton=useRef<HTMLButtonElement>(null)
 const queued=useRef(new Set<UsageProvider>())
 const active=useRef(new Set<UsageProvider>()),mounted=useRef(false)
 const refresh=useCallback(async(provider:UsageProvider,force=false)=>{
  if(active.current.has(provider)){if(force)queued.current.add(provider);return}
  active.current.add(provider);setBusy(old=>({...old,[provider]:true}));setErrors(old=>({...old,[provider]:undefined}))
  try{const data=await readUsage(provider,force);if(mounted.current)setSnapshots(old=>({...old,[provider]:data}))}catch(e){if(mounted.current)setErrors(old=>({...old,[provider]:e instanceof Error?e.message:'조회 실패'}))}finally{active.current.delete(provider);if(mounted.current)setBusy(old=>({...old,[provider]:false}));if(mounted.current&&queued.current.delete(provider))void refresh(provider,true)}
 },[])
 useEffect(()=>{mounted.current=true;const update=()=>{if(!document.hidden)usageProviders.forEach(p=>void refresh(p))};update();const timer=setInterval(update,300000);const clock=setInterval(()=>setNow(Date.now()),30000);document.addEventListener('visibilitychange',update);window.addEventListener('focus',update);return()=>{mounted.current=false;clearInterval(timer);clearInterval(clock);document.removeEventListener('visibilitychange',update);window.removeEventListener('focus',update)}},[refresh])
 useEffect(()=>{for(const p of usageProviders){const s=snapshots[p];if(s?.accounts.some(a=>a.windows.some(w=>w.resetsAt&&Date.parse(w.resetsAt)<=now&&Date.parse(s.checkedAt)<Date.parse(w.resetsAt))))void refresh(p)}},[now,snapshots,refresh])
 const accounts=Object.values(snapshots).flatMap(s=>s?.accounts??[]),linked=accounts.filter(a=>a.identity||a.label!=='현재 로그인'),fresh=linked.filter(a=>a.status==='fresh'&&!quotaIsStale(a,now))
 const beginLogin=async(provider:UsageProvider)=>{setNotice('');setAuthCode('');setLoginBusy(true);try{const state=await startUsageLogin(provider);loginRef.current=state;setLogin(state)}catch(e){setNotice(e instanceof Error?e.message:'로그인을 시작하지 못했어요.')}finally{setLoginBusy(false)}}
 const sendCode=async()=>{if(!login)return;setLoginBusy(true);try{const state=await submitUsageLoginCode(login.id,authCode.trim());setAuthCode('');loginRef.current=state;setLogin(state)}catch(e){setNotice(e instanceof Error?e.message:'인증 코드 확인 실패')}finally{setLoginBusy(false)}}
 const cancelLogin=async()=>{setAuthCode('');if(!loginRef.current)return;try{const state=await cancelUsageLogin(loginRef.current.id);loginRef.current=state;setLogin(state)}catch{setNotice('로그인을 취소하지 못했어요. 다시 시도해 주세요.')}}
 useEffect(()=>{if(login?.status!=='waiting')return;let stopped=false,inFlight=false;const timer=setInterval(async()=>{if(inFlight)return;inFlight=true;try{const state=await usageLoginStatus(login.id);if(stopped)return;loginRef.current=state;setLogin(state);if(state.status==='connected'){setNotice('계정 연결을 완료했어요.');void refresh(state.provider,true)}}catch{if(!stopped)setNotice('로그인 상태 확인에 실패했어요. 다시 확인하고 있어요.')}finally{inFlight=false}},1500);return()=>{stopped=true;clearInterval(timer)}},[login?.id,login?.status,refresh])
 useEffect(()=>()=>{if(loginRef.current?.status==='waiting')void cancelUsageLogin(loginRef.current.id).catch(()=>{})},[])
 const closeConnect=()=>{if(loginBusy||login?.status==='waiting'){setNotice('진행 중인 로그인을 먼저 취소해 주세요.');return}setConnecting(false);setNotice('');connectButton.current?.focus()}

 const patch=(id:string,value:{alias?:string;hidden?:boolean})=>setPreferences({...preferences,[id]:{...preferences[id],...value}})
 return <main className="usage-view"><header><div><h1>AI 사용량</h1><p>계정마다 남은 한도와 다음 초기화 시간을 확인하세요.</p></div><div><button disabled={Object.values(busy).some(Boolean)} onClick={()=>usageProviders.forEach(p=>void refresh(p,true))}><RefreshCw size={15}/>전체 갱신</button><button ref={connectButton} className="usage-primary" onClick={()=>connecting?closeConnect():setConnecting(true)}><Plus size={16}/>계정 연결</button></div></header>
 {connecting&&<section className="usage-connect" aria-label="계정 연결" onKeyDown={e=>{if(e.key==='Escape')closeConnect()}}><button className="usage-connect__close" aria-label="계정 연결 닫기" onClick={closeConnect}><X size={16}/></button><h2>AI 계정 연결</h2><p>서비스를 선택하면 공식 로그인 페이지가 열려요. 로그인 후 이 화면에 계정과 한도가 표시돼요.</p><div className="usage-login-providers">{usageProviders.map(p=><button key={p} disabled={p==='gemini'||loginBusy||login?.status==='waiting'} onClick={()=>void beginLogin(p)}>{usageInfo[p].name} 로그인 <ArrowUpRight size={14}/></button>)}</div><small>계정마다 로그인을 따로 보관해요. 기존 CLI 계정은 변경하지 않아요.</small><small>Gemini: 현재 설치된 CLI에서 앱 내 계정 추가를 지원하지 않아요. 기존 연결의 한도 조회는 가능해요.</small>{login&&<div className="usage-login-status" role="status"><strong>{usageInfo[login.provider].name} · {login.status==='waiting'?'로그인 대기':login.status==='connected'?'연결 완료':login.status==='cancelled'?'취소됨':'연결 실패'}</strong><p>{login.message}</p>{login.status==='waiting'&&login.requiresCode&&<form className="usage-login-code" onSubmit={e=>{e.preventDefault();void sendCode()}}><label>공식 페이지의 인증 코드<input type="password" autoComplete="off" value={authCode} maxLength={4096} onChange={e=>setAuthCode(e.target.value)} placeholder="인증 코드 붙여넣기"/></label><button disabled={!authCode.trim()||loginBusy}>연결 완료</button></form>}{login.status==='waiting'&&<div>{login.url&&<a href={login.url} target="_blank" rel="noreferrer">로그인 페이지 다시 열기 <ArrowUpRight size={14}/></a>}<button onClick={()=>void cancelLogin()}>로그인 취소</button></div>}{(login.status==='error'||login.status==='cancelled')&&<button disabled={loginBusy} onClick={()=>void beginLogin(login.provider)}>다시 시도</button>}</div>}</section>}

 {notice&&<p role="status" className="usage-notice">{notice}</p>}
 <div className="usage-toolbar"><div className="usage-filters" aria-label="서비스 필터">{(['all',...usageProviders] as const).map(p=><button key={p} aria-pressed={filter===p} onClick={()=>setFilter(p)}>{p==='all'?'전체':usageInfo[p].name}</button>)}</div><label><input type="checkbox" checked={showHidden} onChange={e=>setShowHidden(e.target.checked)}/>숨긴 계정</label></div>
 <div className="usage-scroll"><div className="usage-summary"><span><strong>{linked.length}</strong> 확인된 계정</span><span><strong>{fresh.length}</strong> 최신 한도</span><small>5분 자동 갱신 · 서비스 간 한도는 합산하지 않아요</small></div>
 {usageProviders.filter(p=>filter==='all'||filter===p).map(provider=>{const data=snapshots[provider],visible=data?.accounts.filter(a=>showHidden||!preferences[a.id]?.hidden);return <section className="usage-group" key={provider}><div className="usage-group__title"><div><h2>{usageInfo[provider].name}</h2><p>{usageInfo[provider].hint}</p></div><button disabled={busy[provider]} aria-label={`${usageInfo[provider].name} 갱신`} onClick={()=>void refresh(provider,true)}><RefreshCw size={14} className={busy[provider]?'usage-spin':''}/>{busy[provider]?'조회 중':'갱신'}</button></div>{errors[provider]&&<p role="alert" className="usage-notice">{errors[provider]}</p>}<div className="usage-grid">{!data?<article className="usage-card usage-empty"><Gauge size={24}/><p>{busy[provider]?'계정과 한도를 확인하고 있어요…':'조회 결과가 없어요.'}</p></article>:!visible?.length?<article className="usage-card usage-empty"><p>표시할 계정이 없어요.</p><button onClick={()=>setShowHidden(true)}>숨긴 계정 보기</button></article>:visible.map(account=><AccountCard key={account.id} account={account} preferences={preferences[account.id]} onPatch={value=>patch(account.id,value)} now={now} failed={!!errors[provider]} onManage={()=>{setConnecting(true);setNotice(`${usageInfo[provider].name} 로그인을 선택해 계정을 연결해 주세요.`)}} busy={!!busy[provider]}/> )}</div></section>})}
 <p className="usage-footnote">이 화면에서 연결한 계정과 기존 CodexBar 계정을 함께 표시해요. ‘숨기기’는 로그인 상태를 변경하지 않아요.</p></div></main>
}
function AccountCard({account:a,preferences,onPatch,now,failed,onManage,busy}:{account:QuotaAccount;preferences?:Preferences[string];onPatch:(p:Preferences[string])=>void;now:number;failed:boolean;onManage:()=>void;busy:boolean}){
 const [editing,setEditing]=useState(false),[alias,setAlias]=useState('')
 const stale=failed||quotaIsStale(a,now),status=a.status==='fresh'&&stale?'stale':a.status,hasIdentity=!!a.identity||a.label!=='현재 로그인'
 return <article className={`usage-card${preferences?.hidden?' is-hidden':''}`}><div className="usage-card__heading"><div>{editing?<form onSubmit={e=>{e.preventDefault();onPatch({alias:alias.trim()});setEditing(false)}}><input aria-label="계정 별칭" value={alias} maxLength={50} autoFocus onChange={e=>setAlias(e.target.value)}/><button aria-label="별칭 저장"><Check size={14}/></button><button type="button" aria-label="별칭 수정 취소" onClick={()=>setEditing(false)}><X size={14}/></button></form>:<h3>{preferences?.alias||(hasIdentity?a.label:'계정 연결 필요')}</h3>}{a.identity&&a.identity!==(preferences?.alias||a.label)&&<p>{a.identity}</p>}{a.organization&&<small title={a.organization}>{/^[a-f0-9-]{36}$/i.test(a.organization)?`워크스페이스 · ${a.organization.slice(0,8)}`:a.organization}</small>}</div><span className={`usage-badge usage-badge--${status}`}>{statuses[status]}</span></div><div className="usage-scope">{usageInfo[a.provider].scope}{a.plan&&<span>{a.plan}</span>}</div>
 {a.reason&&<p className="usage-reason">{a.reason}</p>}{a.windows.length>0&&<div className={stale||a.status!=='fresh'?'usage-windows is-stale':'usage-windows'}>{(stale||a.status!=='fresh')&&<small>마지막 확인값 · 현재 남은 한도는 재조회가 필요해요</small>}{a.windows.map(w=><div key={w.id} className="usage-window"><div><span>{w.label}</span><strong>{w.remainingPercent===null?'조회 불가':`${Math.round(w.remainingPercent*10)/10}% 남음`}</strong></div>{w.remainingPercent!==null&&<div className={`usage-meter${w.remainingPercent<=10?' is-low':''}`} role="meter" aria-label={`${w.label} 남은 한도`} aria-valuemin={0} aria-valuemax={100} aria-valuenow={w.remainingPercent}><i style={{width:`${w.remainingPercent}%`}}/></div>}<small>{resetLabel(w.resetsAt,now)}</small>{w.resetsAt&&<time dateTime={w.resetsAt}>{new Date(w.resetsAt).toLocaleString('ko-KR')}</time>}{w.remainingPercent===0&&<span className="usage-exhausted">확인 시점에 한도 도달</span>}</div>)}</div>}
 <footer><small>{a.observedAt?`${new Date(a.observedAt).toLocaleString('ko-KR')} 확인`:'성공한 조회 없음'}<br/>출처: CodexBar · {a.source}</small><div>{hasIdentity&&<><button aria-label={`${a.label} 별칭 수정`} onClick={()=>{setAlias(preferences?.alias||a.label);setEditing(true)}}><Pencil size={13}/></button><button aria-label={preferences?.hidden?`${a.label} 다시 표시`:`${a.label} 숨기기`} onClick={()=>onPatch({hidden:!preferences?.hidden})}><EyeOff size={13}/>{preferences?.hidden?'다시 표시':''}</button></>}<a href={usageInfo[a.provider].url} target="_blank" rel="noreferrer" aria-label={`${usageInfo[a.provider].name} 원본 페이지`}><ArrowUpRight size={15}/></a></div></footer>{a.status!=='fresh'&&<button className="usage-reconnect" disabled={busy} onClick={onManage}>연결 확인</button>}</article>
}
